name: Deploy Backend to VPS

on:
  push:
    branches:
      - main  # Adjust based on your branch

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from GitHub
    - name: Checkout Backend Code
      uses: actions/checkout@v3

    # Set up Node.js environment for backend (if you're using Node.js)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.8.0'  # Adjust version as necessary

    # Install dependencies for the backend
    - name: Install Backend Dependencies
      run: npm install

    # Deploy to VPS via SSH
    - name: Deploy Backend to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 7122  # Adjust if using a custom port
        script: |
          # Ensure nvm and Node.js are available
          . ~/.nvm/nvm.sh || echo "nvm not found"  # Load nvm if available
          nvm use 22.8.0 || echo "Using system default Node.js"

          # Navigate to the backend directory
          cd /var/www/back-end/turf-backend

          # Stash local changes to avoid merge conflicts, then pull the latest code
          git stash --include-untracked
          git pull origin main
          git reset --hard origin/main

          # Ensure npm is available and install dependencies
          command -v npm || echo "npm not found"  # Check if npm is accessible
          npm install

          # Start the backend service using pm2 (background process management)
          pm2 start index.js --name "turf-backend"  # or pm2 start server.js
          pm2 save  # Save the pm2 process list
          pm2 startup  # Generate the necessary startup script
